sequenceDiagram
    autonumber
    participant Upstream
    participant agent-assurance
    participant des

    Upstream->>+agent-assurance: GET /agent/agency-details/arn/:arn
    agent-assurance->>+des: GET /registration/personal-details/arn/:arn
    des-->>-agent-assurance: Agent record
    agent-assurance-->>-Upstream: Agency details
