sequenceDiagram
    autonumber
    participant Upstream
    participant agent-assurance
    participant agent-assurance-mongo
    participant des

    Upstream->>+agent-assurance: GET /managed-utrs/utr/:utr
    agent-assurance->>+agent-assurance-mongo: Read: Check if UTR is in 'manually-assured'
    agent-assurance-mongo-->>-agent-assurance: Boolean
    agent-assurance->>+agent-assurance-mongo: Read: Check if UTR is in 'refusal-to-deal-with'
    agent-assurance-mongo-->>-agent-assurance: Boolean
    alt if nameRequired is true
        agent-assurance->>+des: GET /registration/business-details/utr/:utr
        des-->>-agent-assurance: Optional Business Name
    end
    agent-assurance-->>-Upstream: UTR Details
