sequenceDiagram
    autonumber
    participant Upstream
    participant agent-assurance
    participant agent-assurance-mongo

    Upstream->>+agent-assurance: POST /refusal-to-deal-with
    agent-assurance->>+agent-assurance-mongo: Create: Upsert property in 'refusal-to-deal-with' collection
    agent-assurance-mongo-->>-agent-assurance: Success
    agent-assurance-->>-Upstream: 201 Created
